### ISSUE TITLE
[BUG]: Help messages not displayed for individual commands

### ISSUE THREAD

**Issue by Ep1cNeo** [STFCcommunity/botfeedback#11]
**Describe the bug**
Using help as argument for individual commands does not work, this should ideally give details on the specific command usage and options as applicable.

**To Reproduce**
.res help / .off help / .daily help

**Comment by WebSpider** [comment]
We use `.help <cmd>` instead, does that cover this sufficiently ?

**Comment by Ep1cNeo** [comment]
Yeah, should be fine. Opened since it used to work either way with LCARS.

**Comment by Iliasgx** [comment]
Both ways are now possible.
