### ISSUE TITLE
[REQ]: add menu option for recycling info to ship menu

### ISSUE THREAD

**Issue by ccMatrix** [STFCcommunity/botfeedback#12]
When starting the command `.scrap` the menu let's you navigate through faction, ship type and so on. But when a ship is selected only options like tier information, total cost of ownership etc. are listed and there is no way to get to the recycling info.

There could be an option to allow the user to select the recycling info there as well. To reduce clutter that option would jump to the max level scrap info. An additional info could let the user know how he can jump directly to the scrap info with an explicit level.

![Screenshot_20210810-202344_Discord](https://user-images.githubusercontent.com/96917/128918141-940aeedb-b7aa-465e-b0c6-f8ea1b449009.jpg)

**Comment by Iliasgx** [comment]
Implemented
