### ISSUE TITLE
[BUG]: Hostile Command returning incorrect results

### ISSUE THREAD

**Issue by Ep1cNeo** [STFCcommunity/botfeedback#13]
**Describe the bug**
Looking up hostiles is not working for faction/type specific, it looks to be matching on other criteria.

**To Reproduce**
.hostile fed sur 24

**Expected behavior**
Federation Survey hostiles level 24 should be listed

**Screenshots**
![Hostile Fed Sur 24](https://user-images.githubusercontent.com/88446290/130327038-fc43a17d-67e1-47aa-9995-72cf33c0c44a.png)

**Comment by Iliasgx** [comment]
Issue resolved
