### ISSUE TITLE
[BUG]: Scrap command giving unrelated info

### ISSUE THREAD

**Issue by WebSpider** [STFCcommunity/botfeedback#14]
**Describe the bug**
The scrap command without any arguments gives feedback that doesnt help the user
This is a port of STFCcommunity/data#80 to the correct repo

**To Reproduce**
```txt
MrHamster — Today at 8:14 PM
.scrap
KMARS beta
BOT
— Today at 8:15 PM
Choose the type of information you like
Please choose which information you would like to view for the uss franklin-a from the list below:
Choices
:one: Tier information

:two: Total Cost of Ownership (TCO)

:three: Scrap Information

:four: Blueprints

:five: Summaries

:six: Ship skins
```
**Expected behavior**
Display information about just the `scrap` command

**Comment by Iliasgx** [comment]
Output improved for no-argument command.
