### ISSUE TITLE
[BUG]: Alliancelevel command does not work as expected for level 1

### ISSUE THREAD

**Issue by WebSpider** [STFCcommunity/botfeedback#15]
**Describe the bug**
The Alliancelevel <level> command does not work for level 1 alliance
This is a duplicate of STFCcommunity/data#73

**To Reproduce**
```text
[34-DRED] MrHamster — Today at 7:23 PM
.alliancelevel 1
KMA Beta
BOT
— Today at 7:23 PM
That did not work
Alliance levels go from 1 to 50. Please try again
KMARS beta - 382da2b•Today at 7:23 PM
```

**Expected behavior**
For level 1 to work like all outher levels 2-50

**Comment by Iliasgx** [comment]
Issue resolved
