### ISSUE TITLE
[BUG]: Attempting a documented example for armadas doesnt work

### ISSUE THREAD

**Issue by WebSpider** [STFCcommunity/botfeedback#16]
**Describe the bug**
Type the command listed below which is a documented example of armadas
This is a duplicate of STFCcommunity/data#81

**To Reproduce**
```text
MrHamster — Today at 8:20 PM
.arm uncommon 30 to 35
KMARS beta
BOT
— Today at 8:20 PM
Oops, something went wrong Commander. scream
Please contact a Bot Team member and explain what happened.
```

**Expected behavior**
Either don't list it as an example, or make it work :)

**Comment by Iliasgx** [comment]
The bot tried to perform a substring search with `to` for the armada name. This is now resolved.
