### ISSUE TITLE
.bp sal.... doesn't work but .bp ent does.

### ISSUE THREAD

**Issue by hamilton1977** [STFCcommunity/botfeedback#18]
[34-DRED] MrHamster — Today at 7:50 PM
.bp sal
KMA Beta
BOT
 — Today at 7:50 PM
Sorry Commander, I haven't found a ship with this name or alias.

-----
Not sure what other ship has "sal" but if there is to maybe list both. but, this says sal isn't there.

**Comment by hamilton1977** [comment]
yeap.  most ppl call it a sal or sally.  so, if given 3 letters then see if it matches anything related to the command given.  if it returns more then just one item give options that are related to the command given. 

I didn't go down the full list of ships to see if any others returned something. 

😇 but i will soon 😍

**Comment by WebSpider** [comment]
`sal` was added as an alias to `USS Saladin`, so this should work now.
