### ISSUE TITLE
[BUG]: Research and Buildings dont have their requirements listed 

### ISSUE THREAD

**Issue by WebSpider** [STFCcommunity/botfeedback#2]
**Describe the bug**
[Admin] LostandFound
 — 
Yesterday at 10:15 PM
@WebSpider can you submit a error report to the github for me cause I can't remember my github info? Research and buildings don't have their requirements listed, the prerequisites

**To Reproduce**
1. Type the command to display the research/building you want (.b operations 42)
2. Watch requirements being empty

**Expected behavior**
Display the correct requirement

**Additional context**
Copy/paste from discord

**Comment by Iliasgx** [comment]
Requirements are listed now for both.
