### ISSUE TITLE
[REQ]: Additional columns for research/building summary that show power increased/power earned

### ISSUE THREAD

**Issue by nfoboy** [STFCcommunity/botfeedback#25]
**Is your feature request related to a problem? Please describe.**
When pulling up summary information, it is very useful to know what the power increase for each level of a research/building is.  This allows for very quick multi-level power information to be calculated, instead of having to look up each individual level to get to that information.  Additionally, the Ops level that is required for each level is also very handy.

Feel free to add screenshots of you feel that makes your description clearer
Current:
![image](https://user-images.githubusercontent.com/5087665/133938798-2b21b589-ad75-4f81-a74d-cd04c351985a.png)

**Describe the solution you'd like**
Proposed:
![image](https://user-images.githubusercontent.com/5087665/133938759-cc684844-1263-4ed1-8a2c-6b0f5d6d6fb5.png)

**Describe alternatives you've considered**
No alternatives considered.

**Additional context**

**Comment by WebSpider** [comment]
This seems like a useful and not too difficult fix, thanks for suggesting it!

**Comment by WebSpider** [comment]
This has been implemented
