### ISSUE TITLE
Command to find ship tiers info is counterintuitive

### ISSUE THREAD

**Issue by Bandit2710** [STFCcommunity/botfeedback#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by WebSpider** [comment]
We need to use the argument parser here to make random orders possible

**Comment by Bandit2710** [comment]
What the what now

**Comment by WebSpider** [comment]
eg: !gm_ship tier Stella 7 makes no sense it should be !gm_ship Stella t7 or tier 7

**Comment by WebSpider** [comment]
@Bandit2710 can you please check again using the new `.ship` command ?

**Comment by Bandit2710** [comment]
Resolved
