### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by abmmrusso** [STFCcommunity/botfeedback#30]
**Describe the bug**
Calling for resources for Augment systems causes the Bot to report an error.

**To Reproduce**
1. Go to any of the `terminal-x` channels
2. Type command `.resource <augment system name>` (for example, `.resource lydan` or `.resource rainsford`)
4. See bot reporting an issue

**Expected behavior**
I would expect the bot to display information on Corrupted/Decoded Data mining resources

**Screenshots**
![image](https://user-images.githubusercontent.com/1713237/144600800-9d1ae377-eac4-42d4-884d-e8599cb6aaa4.png)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser: Chrome
 - Version: 96.0.4664.55 (Official Build) (x86_64)

**Additional context**
Is this derived from the absence of mining data for said systems like seen for Lydan (https://github.com/STFCcommunity/data/blob/main/systems/lydan_22.json#L17) or Rainsford (https://github.com/STFCcommunity/data/blob/main/systems/rainsford_20.json#L21) and lack of support of the bot for Decoded/Corrupted Data resource types?

**Comment by Iliasgx** [comment]
Yes, that data has not been added apparently, which the bot considers as a problem. Thank you for informing us.

**Comment by abmmrusso** [comment]
Is there an open ticket somewhere to add said data in?
As the repo is public, I ended up cloning it and changing the json files to have data on resources but have been wondering what the correct way to submit this information for approval is.

**Comment by Iliasgx** [comment]
When the changes are conform the json schema, please use `pre-commit run -a` to reformat the files if needed. After that, you can just start a pull request in the repo.

**Comment by abmmrusso** [comment]
Have raised PR https://github.com/STFCcommunity/data/pull/124 for review to add the missing data.

**Comment by Iliasgx** [comment]
Implemented
