### ISSUE TITLE
Separate messages when the timer ends and when the user chooses to end the session manually

### ISSUE THREAD

**Issue by KingoAG02** [STFCcommunity/botfeedback#4]
**Is your feature request related to a problem? Please describe.**
Currently, KMARS sends the same message when the 60s timer ends, and when the user manually ends the session by reacting with the X emote

**Describe the solution you'd like**
A separate message, something along the lines of "your *KMARS* session has been terminated, have a nice day" when the X reaction is chosen, and a "you took too long to respond, please re-enter the command to restart the *KMARS* session"

**Comment by WebSpider** [comment]
Need to implement this for all multiple choices:
Officers
Ships
All of them

**Comment by WebSpider** [comment]
I've reimplmented this for all occurrences i could find, can you check?
