### ISSUE TITLE
[BUG]: bot only accepts .factionrep and not .factionreputation

### ISSUE THREAD

**Issue by Bandit2710** [STFCcommunity/botfeedback#5]
**Describe the bug**

**To Reproduce**
1. Go to 'disc
2. Type .factionrep and then .factionreputation 
.'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by WebSpider** [comment]
This is being added to the bot now.
