### ISSUE TITLE
[REQ]: Add explanation for TCO in ship command

### ISSUE THREAD

**Issue by WebSpider** [STFCcommunity/botfeedback#8]
**Is your feature request related to a problem? Please describe.**
[Admin] TheLooter — Today at 6:51 AM
I don’t have a GitHub account atm, but might be worth adding what “TCO” is in brackets for ship command @Chief Bot Engineering Officers

**Describe the solution you'd like**
Explain what TCO means in ship command

**Comment by Iliasgx** [comment]
TCO explanation added to the bot.
