### ISSUE TITLE
[BUG]: Bot response missing for incorrect arguments

### ISSUE THREAD

**Issue by Ep1cNeo** [STFCcommunity/botfeedback#9]
**Describe the bug**
Bot does not respond with an error message or text when the arguments are not valid/applicable. 

**To Reproduce**
.off spock rank / .off spock a

**Expected behavior**
A clear and descriptive message specifying if the command is invalid or data not present etc.

**Comment by WebSpider** [comment]
We will be reimplementing the officer command, and this will be added to the list of things to fix. Thanks for your feedback!

**Comment by WebSpider** [comment]
Resolved
